In [4]:
# Let's bring in numpy first
import numpy as np

In [6]:
x = np.array([1,4,6,6,8])
x

array([1, 4, 6, 6, 8])

In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(5,)

In [10]:
x.size

5

In [11]:
x.dtype

dtype('int32')

In [12]:
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [13]:
x[0,]

1

In [14]:
x[5,]

6

In [16]:
x[:4]

array([1, 2, 3, 4])

In [17]:
np.save('x', x)

In [18]:
np.load("x.npy")
x

array([1, 2, 3, 4, 5, 6])